# Gender Detection

In [1]:
import os
import numpy as np
from keras.preprocessing import image
import cv2
import dlib
import pandas as pd
import matplotlib.pyplot as plt
import sys

Using TensorFlow backend.


In [2]:
from keras.preprocessing import image
from sklearn import svm, datasets
from sklearn.dummy import DummyClassifier
from sklearn.svm import SVC
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, GridSearchCV, learning_curve, ShuffleSplit
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# Data Preprocessing

In [3]:
# Loading the data file
data = load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
#print(df.head())

# Drop rest of the features and extract the target values
Y = data.target
X = data.data[:, :2]

# Shuffle and split the data into training and test set
X, Y = shuffle(X,Y)
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.7)

In [4]:
def SVM(x_train,y_train, x_test):
    #model = ...
    model = SVC(kernel = 'linear')
    model.fit(x_train,y_train)
    #model.  #fit using x_train and y_train
    y_pred = model.predict(x_test)
    return y_pred
# Scikit learn library results
y_pred=SVM(x_train,y_train, x_test)
print(accuracy_score(y_test,y_pred))


0.8


In [5]:
import landmarks as l2

In [6]:
def get_data():

    X, y = l2.extract_features_labels()
    print(X, y)
    Y = np.array([y, -(y - 1)]).T
    tr_X = X[:100]
    tr_Y = Y[:100]
    te_X = X[100:]
    te_Y = Y[100:]

    return tr_X, tr_Y, te_X, te_Y

In [7]:
# sklearn functions implementation
def img_SVM(training_images, training_labels, test_images, test_labels):
    #classifier = ...
    classifier = SVC(kernel = 'rbf')
    classifier.fit(training_images, training_labels)
    pred = classifier.predict(test_images)
    print("Accuracy:", accuracy_score(test_labels, pred))

    print(pred)
    return pred

tr_X, tr_Y, te_X, te_Y= get_data()
pred=img_SVM(tr_X.reshape((100, 68*2)), list(zip(*tr_Y))[0], te_X.reshape((36, 68*2)), list(zip(*te_Y))[0])

[0. 0. 0. ... 1. 1. 1.]
[[[ 59 113]
  [ 57 123]
  [ 57 133]
  ...
  [ 88 163]
  [ 83 163]
  [ 78 161]]

 [[ 55 110]
  [ 54 120]
  [ 54 131]
  ...
  [ 89 163]
  [ 83 163]
  [ 78 161]]

 [[ 42 124]
  [ 43 134]
  [ 46 144]
  ...
  [ 92 148]
  [ 87 148]
  [ 83 148]]

 ...

 [[ 50 112]
  [ 50 123]
  [ 50 134]
  ...
  [ 92 158]
  [ 87 158]
  [ 82 157]]

 [[ 39 116]
  [ 39 128]
  [ 39 141]
  ...
  [ 96 154]
  [ 91 154]
  [ 86 154]]

 [[ 59 106]
  [ 58 116]
  [ 59 127]
  ...
  [ 89 161]
  [ 83 160]
  [ 79 158]]] [0. 0. 0. ... 1. 1. 1.]


ValueError: cannot reshape array of size 638928 into shape (36,136)